"""empty message

Revision ID: 63311b6deea3
Revises: 3569e4ba5395
Create Date: 2026-03-20 20:03:53.434213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63311b6deea3'
down_revision = '3569e4ba5395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('posti_totali', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aula_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('aula_fissata', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_aula_id', 'aula', ['aula_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corso', schema=None) as batch_op:
        batch_op.drop_constraint('fk_aula_id', type_='foreignkey')
        batch_op.drop_column('aula_fissata')
        batch_op.drop_column('aula_id')

    op.drop_table('aula')
    # ### end Alembic commands ###
