"""added presenza

Revision ID: e8ee9987a895
Revises: 
Create Date: 2025-04-12 16:48:37.166899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ee9987a895'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presenza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente', sa.Integer(), nullable=True),
    sa.Column('corso', sa.Integer(), nullable=True),
    sa.Column('presente', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['corso'], ['corso.id'], ),
    sa.ForeignKeyConstraint(['utente'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presenza')
    # ### end Alembic commands ###
